### ISSUE TITLE
RFE: CompactMoon Options should have more color (especially dark) schemes

### ISSUE THREAD

**Issue by TPS** [Lootyhoof/compactmoon#1]
@Lootyhoof Especially _your_ dark themes, but others, too:
* __https://github.com/Lootyhoof/darkpitch__ 
* https://github.com/Lootyhoof/darkmoon
* https://github.com/Lootyhoof/australium
* https://github.com/Lootyhoof/fox2themoon

There really do need to be dark themes customizable like the standard CompactMoon.

**Comment by Lootyhoof** [comment]
Sorry for the late reply, but what would you be looking for with respect to options for other themes?

The main feature of Compact Moon Options (changing how big/small things are) is not going to work well with other themes and I do not want to introduce it.

**Comment by TPS** [comment]
Then maybe the other way around, i.e, make Compact Moon have options to look like other themes? E.g., ___I___ especially appreciate (& use) your Dark\* themes, but I miss the screen estate that Compact Moon freed up.

**Comment by Lootyhoof** [comment]
This is possible, to an extent, and I may look into it.

**Comment by TPS** [comment]
@Lootyhoof Just bumping: I really miss CompactMoon's screen real-estate, but [DarkPitch](https://github.com/Lootyhoof/darkpitch) is virtually visually perfect for me otherwise.  I was hoping you'd a chance to think about this.  

For a quick-&-dirty workaround, are their assets laid out similarly?  Would, e.g., copying images from DP into CM make this somewhat functional?

**Comment by Lootyhoof** [comment]
>For a quick-&-dirty workaround, are their assets laid out similarly?

No. It's not that simple, unfortunately.

I will be addressing this, it just takes time given I've other themes to address first.

**Comment by TPS** [comment]
Thanks, I really appreciate it.

**Comment by TPS** [comment]
@Lootyhoof Are some of the recent flurry of commits preliminary work on this?  (Somethings I see look like such.… 🤞)

**Comment by Lootyhoof** [comment]
Yes, the work has been ongoing since https://github.com/Lootyhoof/compactmoon/commit/b00504f3e2bb6012884416e9ac30e4ffb85914d8 (I got a little sidetracked during then for other bugs in other themes). It's a rather large update, but includes a lot of new features and fixes in addition to dark mode (which has not yet been added, but is certainly possible now).

**Comment by TPS** [comment]
Fantastic!  Do lemme know if you want testing/feedback/whatever: I'm happy to help, though not really a coder.

**Comment by Lootyhoof** [comment]
`v2.0.0b1` is out now, check the [releases](https://github.com/Lootyhoof/compactmoon/releases) page. I'd appreciate if you could check it out and let me know of any issues. Check the [changelog](https://github.com/Lootyhoof/compactmoon/blob/master/CHANGELOG.md) for details on other changes. Of note, you'll find the relevant options within the Compact Moon Options window.

This dark theme should also work reasonably well with personas, assuming you use another extension such as [ThemeTool](https://addons.palemoon.org/addon/themetool/).

Thanks!

**Comment by TPS** [comment]
Installing now.... I guess no hope to make them restartless? I'll post back after I restart & play w/ them some.  Thanks!

**Comment by Lootyhoof** [comment]
It's not possible to make themes restartless due to needing to takeover overlays in use, and have no plans to make the extension restartless, sorry.

**Comment by TPS** [comment]
So far, fantastic, other than 1 color detail that's probably a conflict w/ another addon.  I'll post if I can't resolve that way.

**Comment by TPS** [comment]
IMHO, time to release. (That _was_ a conflict with an officially unsupported addon; disabling it fixed it).  This is pretty much everything I wanted! :raised_hands:

**Comment by Lootyhoof** [comment]
Out of curiosity, which addon was it?

I'll do some more cleanup and testing and probably release in a couple days.

**Comment by TPS** [comment]
[LocationBar³](https://addons.mozilla.org/addon/locationbar³/)
