### ISSUE TITLE
Miscalculation (?) in field height: Address bar vs Search bar

### ISSUE THREAD

**Issue by ghost** [Lootyhoof/compactmoon#2]
As mentioned previously in the Pale Moon forum there is a slight miscalculation in the heights of the Address bar and Search bar fields.
Not sure if this depends on the OS and/or other elements used in building the browser GUI.
The issue is observed in the Linux GTK3 version of Pale Moon, the official tarball from the site.
It has been like that for a long time, regardless of the theme version or browser version. Currently: theme **2.8.0** in Pale Moon **31.0.0**.
Screenshots of the issue as well as the settings used for the theme follow:
![Screenshot from 2022-05-12 04-43-14_edit](https://user-images.githubusercontent.com/29117024/167977428-b942b859-d7e9-45b2-b19f-a6b0cf3ac6a3.png)
![CompactMoon_settings](https://user-images.githubusercontent.com/29117024/167977448-a8c3d4ec-f7ee-4646-bcd2-32ca99e58da4.png)

**Comment by Lootyhoof** [comment]
I don't see these issues personally. 

![Pale Moon](https://i.imgur.com/gd2wDKq.png)

I'm also on Linux GTK3, Arch Linux. Have you tried disabling your add-ons? I see at least one that places an icon in the urlbar, but I'd advise just disable as many as possible, one by one, to find the cause.

**Comment by ghost** [comment]
The one you're referring to is RealityRipple's **[GeoFlag](https://realityripple.com/Software/XUL/GeoFlag/)**. That could - theoretically - disturb the theme making the control 1px shorter in height, however the Search bar shows the opposite effect: its height is 1px higher than normal, and there is nothing additional or modified there. Unless there somehow is some weirdly-sized icon in any of the search engines and the field height is automatically calculated by the Max() of those values. Have no idea how these calculations are performed and where.

_Disabling extensions is not such an easy task as it might seem, considering this is a very old profile and the order in which they have been installed and enabled does bare a certain degree of importance in their behavior. Such advice should always be accompanied by a warning regarding potential issues and an advice for backing up the current browser profile._

To the task at hand.
I've just installed GeoFlag in a relatively fresh profile where this issue was not present and it didn't affect the sizes.
Then copied all XML files for the search engines from the affected profile to the fresh profile; again, no change in fields' height.
Then started installing one by one certain add-ons that would put buttons in the toolbar. Finally found the one that created all this disruption: **[butWhyMod v1.7](https://addons.palemoon.org/addon/butwhymod/)**.
Can't remember how I found about it but it has been installed for a long time although it didn't seem to do much good.

**Moving the 'butWhyMod v1.7' button to the statusbar fixed the issue.**

Will now remove all add-ons installed for testing purposes but their presence may still remain registered somewhere in the profile database so this can no longer be considered a fresh profile.
Thank you for finally pushing me into hunting down and finding the culprit. Should've done it by myself long ago but there's always something more important to do at every one moment. One down, a lot more others to go.

Hopefully this will help other users experiencing same or similar issue. All the best and good luck ahead!
